name: Bug提交
description: 向我们报告一个Bug以帮助我们改进MSL
title: "[Bug]: "
labels: ["漏洞bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        感谢您向我们提交BUG！
  - type: checkboxes
    id: check
    attributes:
      label: 检查
      description: 警告:在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
      options:
        - label: 我确认我使用的是 [最新版本](https://mslx.mslmc.cn/docs/install/start/) 的MSLX.
          required: true
        - label: 我确认我已经安装了[.NET Core 10.0](https://mslx.mslmc.cn/docs/install/start/).
          required: true
        - label: 我确认我提交的问题没有人提交过.
          required: true
  - type: textarea
    id: Bug
    attributes:
      label: 描述 Bug
      description: 仔细描述BUG。
      placeholder: 仔细描述BUG。
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 如何复现BUG？
      description: 如何复现BUG？请详细描述步骤！
    validations:
      required: true
  
  - type: dropdown
    id: os_type
    attributes:
      label: 操作系统类型
      description: MSLX 运行在哪种系统上？
      options:
        - Windows
        - Linux
        - macOS
        - Docker
        - Other
    validations:
      required: true
      
  - type: input
    id: os_version
    attributes:
      label: 系统详细版本
      description: 请填写具体的系统版本号或发行版信息。
      placeholder: 例如：Windows 11 23H2, Ubuntu 22.04 LTS, macOS Sonoma 14.2
    validations:
      required: true