namespace MSLX.Daemon.Utils.McdrConfig;

/// <summary>
/// MCDReforged config.yml 生成选项
/// </summary>
public class McdrConfigOptions
{
    /// <summary>MCDR 显示语言</summary>
    public string Language { get; set; } = "zh_cn";

    /// <summary>服务端工作目录(真实 MC 服务端所在的子目录)</summary>
    public string WorkingDirectory { get; set; } = "server";

    /// <summary>启动真实服务端的命令(相对 WorkingDirectory 执行)</summary>
    public string StartCommand { get; set; } = "java -jar server.jar nogui";

    /// <summary>解析服务端输出所用的 handler</summary>
    public string Handler { get; set; } = "vanilla_handler";

    /// <summary>MCDR -> 服务端 stdin 编码</summary>
    public string Encoding { get; set; } = "utf8";

    /// <summary>服务端 stdout -> MCDR 解码</summary>
    public string Decoding { get; set; } = "utf8";

    /// <summary>
    /// 高级控制台。MSLX 会重定向 MCDR 的 stdin/stdout，
    /// 因此必须关闭高级控制台(prompt-toolkit)，否则无法正常收发数据。
    /// </summary>
    public bool AdvancedConsole { get; set; } = false;

    /// <summary>插件安装时传给 pip 的额外参数(如镜像源),留空表示不设置</summary>
    public string? PluginPipInstallExtraArgs { get; set; }
}

/// <summary>
/// 纯逻辑：MCDReforged config.yml 生成、handler 推断、start_command 构建。
/// 不涉及任何 IO，方便单元测试。
/// </summary>
public static class McdrConfigGenerator
{
    /// <summary>
    /// 根据服务端核心文件名推断合适的 MCDR handler。
    /// 参考 MCDR 官方 handler 说明。
    /// </summary>
    public static string InferHandler(string? coreName)
    {
        var name = (coreName ?? string.Empty).ToLowerInvariant();

        if (name.Contains("arclight")) return "arclight_handler";
        if (name.Contains("catserver")) return "cat_server_handler";

        // Mohist / Paper / Folia 等 Bukkit 系(含混合端)统一使用 bukkit_handler
        if (name.Contains("mohist") || name.Contains("paper") || name.Contains("purpur") ||
            name.Contains("folia") || name.Contains("leaves") || name.Contains("leaf") ||
            name.Contains("spigot") || name.Contains("bukkit") || name.Contains("banner"))
        {
            return "bukkit_handler";
        }

        // NeoForge / Forge
        if (name.Contains("forge")) return "forge_handler";

        // 代理端
        if (name.Contains("velocity")) return "velocity_handler";
        if (name.Contains("waterfall")) return "waterfall_handler";
        if (name.Contains("bungee")) return "bungeecord_handler";

        // Fabric / Quilt / Carpet / Vanilla 及其它默认走 vanilla_handler
        return "vanilla_handler";
    }

    /// <summary>
    /// 构建真实服务端的启动命令(shell 字符串形式)。
    /// 命令相对 MCDR 的 working_directory 执行，因此 coreName 应为相对该目录的文件名。
    /// </summary>
    public static string BuildStartCommand(string? javaToken, int? minM, int? maxM, string? extraArgs, string? coreName)
    {
        var java = string.IsNullOrWhiteSpace(javaToken) ? "java" : javaToken.Trim();
        // Java 路径含空格时需要加引号(shell 模式)
        if (java.Contains(' ') && !java.StartsWith('"'))
        {
            java = $"\"{java}\"";
        }

        var parts = new List<string> { java };

        if (minM is > 0) parts.Add($"-Xms{minM}M");
        if (maxM is > 0) parts.Add($"-Xmx{maxM}M");

        if (!string.IsNullOrWhiteSpace(extraArgs))
        {
            parts.Add(extraArgs.Trim());
        }

        var core = string.IsNullOrWhiteSpace(coreName) ? "server.jar" : coreName.Trim();

        // NeoForge/Forge 新版以 @libraries/.../args.txt 形式启动，不需要 -jar
        if (core.StartsWith('@') || core.Contains("@libraries"))
        {
            parts.Add(core);
        }
        else
        {
            parts.Add("-jar");
            parts.Add(core);
        }

        parts.Add("nogui");

        return string.Join(' ', parts);
    }

    /// <summary>
    /// 生成完整的 config.yml 文本。缺失的其余配置项将由 MCDR 首次启动时补全为默认值。
    /// </summary>
    public static string Generate(McdrConfigOptions options)
    {
        var pip = string.IsNullOrWhiteSpace(options.PluginPipInstallExtraArgs)
            ? string.Empty
            : " " + YamlSingleQuote(options.PluginPipInstallExtraArgs);

        var lines = new List<string>
        {
            "# The configuration file for MCDReforged",
            "# Generated by MSLX (Minecraft Server Launcher X)",
            "# See https://docs.mcdreforged.com/en/latest/configuration.html for more details",
            "",
            $"language: {options.Language}",
            "",
            $"working_directory: {options.WorkingDirectory}",
            "",
            $"start_command: {YamlSingleQuote(options.StartCommand)}",
            "",
            $"handler: {options.Handler}",
            "",
            $"encoding: {options.Encoding}",
            $"decoding: {options.Decoding}",
            "",
            "rcon:",
            "  enable: false",
            "  address: 127.0.0.1",
            "  port: 25575",
            "  password: ''",
            "",
            "plugin_directories:",
            "- plugins",
            "",
            "catalogue_meta_cache_ttl: 1200",
            "catalogue_meta_fetch_timeout: 15",
            "catalogue_meta_url:",
            "plugin_download_url:",
            "plugin_download_timeout: 15",
            $"plugin_pip_install_extra_args:{pip}",
            "",
            "check_update: true",
            // MSLX 重定向了 stdio，必须关闭高级控制台
            $"advanced_console: {(options.AdvancedConsole ? "true" : "false")}",
            "telemetry: false",
            "",
            "disable_console_thread: false",
            "disable_console_color: false",
            "watchdog_threshold: 10",
            "handler_detection: true",
            ""
        };

        return string.Join("\n", lines);
    }

    /// <summary>
    /// 生成一份最小可用的 permission.yml(仅在实例尚无该文件时使用)。
    /// </summary>
    public static string GenerateDefaultPermission()
    {
        var lines = new[]
        {
            "# The permission configuration file for MCDReforged",
            "# Generated by MSLX",
            "default_level: user",
            "owner:",
            "admin:",
            "helper:",
            "user:",
            "guest:",
            ""
        };
        return string.Join("\n", lines);
    }

    /// <summary>
    /// 将字符串包装为 YAML 单引号标量，转义内部单引号。
    /// 用于可能包含冒号/反斜杠(如 Windows 路径)的值。
    /// </summary>
    private static string YamlSingleQuote(string? value)
    {
        value ??= string.Empty;
        return "'" + value.Replace("'", "''") + "'";
    }
}
