name: Build and Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - { os: linux, arch: x64, runtime: linux-x64 }
          - { os: linux, arch: arm64, runtime: linux-arm64 }
          - { os: windows, arch: x64, runtime: win-x64 }
          - { os: windows, arch: arm64, runtime: win-arm64 }
          - { os: osx, arch: arm64, runtime: osx-arm64 }
    steps:
      - uses: actions/checkout@v4

      - name: Update Submodule
        run: git submodule update --init --recursive
        
      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build for Linux/Windows
        continue-on-error: true
        if: matrix.os != 'osx'
        run: |
          dotnet publish -c Release -r ${{ matrix.runtime }} \
            --self-contained true \
            -p:PublishSingleFile=false \
            -p:PublishTrimmed=false \
            -o ./publish/${{ matrix.os }}-${{ matrix.arch }}  --framework net8.0

      - name: test
        if: matrix.os == 'osx'
        run: dotnet restore -r ${{ matrix.runtime }}
        
      - name: Build for macOS
        continue-on-error: true
        if: matrix.os == 'osx'
        run: |
          dotnet msbuild -t:BundleApp \
            -p:RuntimeIdentifier=${{ matrix.runtime }} \
            -property:Configuration=Release \
            -p:UseAppHost=true \
            -p:OutputPath=./publish/osx-${{ matrix.arch }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MSLX.Desktop-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ./publish/${{ matrix.os }}-${{ matrix.arch }}/**
            !**/*.pdb
          if-no-files-found: error
